import type { Metadata } from "next";
import "./globals.css";
import Sidebar, { Navbar } from "@/components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <div className="flex">
            <Sidebar />
            <Navbar />
            <div className="flex-1 flex flex-col">
              <div>
                <Header />
              </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
